version: '3.9'

services:
  create:
    build: .
    # runtime: nvidia
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]
    volumes:
      - /mnt/mydisk/models/gocomments:/workspace/runs
      - ../model:/app/scripts
      - ../dataset/file:/app/scripts/dataset
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/lib/tensorflow:$LD_LIBRARY_PATH
    # command: /bin/bash -c "tail -f /dev/null"
    command: python3 /app/scripts/train.py
    # shm_size: '2gb'
    ipc: host