version: '3.8'

services:
  test-api:
    build: ../model/.
    image: tokenizer_image
    volumes:
      - ../runs:/workspace/runs
      - ../api:/app/scripts
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/lib/tensorflow:$LD_LIBRARY_PATH
    container_name: tokenizer_api
    command: python3 /app/scripts/tokenizer_api.py
    ports:
      - "5000:5000"

  go-tf-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - test-api
    volumes:
      - .:/app
      - ../runs:/workspace/runs
      - ../dataset/file:/app/dataset
    command: ["sh", "-c", "go build -o /bin/myapp . && /bin/myapp"]
