version: '3.8'

services:
  go-tf-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ../dataset/file:/app/dataset
    command: ["sh", "-c", "go build -o /bin/myapp . && /bin/myapp"]
