version: '3.8'

services:
  go-tf-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ../dataset/file:/app/dataset
      - ../runs/checkpoint_model/checkpoint-tf-6:/app/models
    ports:
      - "8080:8080"
    command: ["sh", "-c", "go build -o /bin/myapp . && /bin/myapp"]
