version: '3.8'

services:
  tokenizer:
    build: ../model/.
    image: tokenizer_image
    volumes:
      - ../runs:/workspace/runs
      - .:/app/scripts
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/lib/tensorflow:$LD_LIBRARY_PATH
    container_name: tokenizer_container
    command: python3 /app/scripts/tokenizer_api.py
