version: '3.8'

services:
  go-tf-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ../runs/saved_model_20240622:/app/models
    ports:
      - "8080:8080"
    command: ["sh", "-c", "go build -o myapp . && ./myapp"]
