version: '3.8'

services:
  tokenizer:
    build: ../model/.
    image: tokenizer_image
    volumes:
      - ../runs:/workspace/runs
      - .:/app/scripts
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/lib/tensorflow:$LD_LIBRARY_PATH
    container_name: tokenizer_container
    command: python3 /app/scripts/tokenizer_api.py

  go-tf-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - tokenizer
    volumes:
      - .:/app
      - ../dataset/file:/app/dataset
      - ../runs/checkpoint_model/checkpoint-tf-7:/app/models
    command: ["sh", "-c", "go build -o /bin/myapp . && /bin/myapp"]
